### ISSUE TITLE
Why Ruby 2.3?

### ISSUE THREAD

**Issue by mrmarbury** [newcontext/kitchen-terraform#30]
Hi,

this is just a question that bothers me/us. Why do you only support Ruby 2.3? Is there a special 2.3 feature you are using? Or was this just for convenience?  Because this makes it so much harder to use it with ChefDK which uses Ruby 2.1.8. 

Cheers,
Stefan

**Comment by ncs-alane** [comment]
Thanks for your interest in the project.

Ruby 2.3 was chosen because it's the latest release; as this project is not directly related to Chef, we were not focused on ensuring compatibilty with the Chef Development Kit. 

Once we have a proper CI/CD pipeline set up, we can explore supporting older versions of Ruby, but until then, we recommend that you work with the project as outlined in the README.

**Comment by mrmarbury** [comment]
okay, thank you
